/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 * Classe che crea l'interfaccia grafica del programma
 * @author Andrea Del Corto-Simone Giacomelli 5IA-07
 */
public class MyFrame extends javax.swing.JFrame {
    private Grafo g;


    /**
     * Creates new form MyFrame
     */
    public MyFrame() {
        initComponents();
        //g = new Grafo(10);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField_numNodi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_confNumNodi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_startLink = new javax.swing.JTextField();
        jLabel_confLink = new javax.swing.JLabel();
        jTextField_endLink = new javax.swing.JTextField();
        jTextField_pesoLink = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_startDijkstra = new javax.swing.JTextField();
        jLabel_confDijkstra = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_grafoStruct = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_result = new javax.swing.JTextArea();
        jTextField_endDijkstra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 25)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Graph Manager");
        jLabel2.setToolTipText("");

        jTextField_numNodi.setColumns(3);
        jTextField_numNodi.setToolTipText("Inserisci numero di nodi");
        jTextField_numNodi.setName(""); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("./resources/logo.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("./resources/logo.png"))); // NOI18N

        jLabel_confNumNodi.setIcon(new javax.swing.ImageIcon(getClass().getResource("./resources/newNodo.png"))); // NOI18N
        jLabel_confNumNodi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_confNumNodiMouseClicked(evt);
            }
        });

        jLabel1.setText("Numero nodi:");

        jLabel6.setText("Nuovo collegamento:");

        jTextField_startLink.setColumns(3);
        jTextField_startLink.setToolTipText("Nodo di partenza");
        jTextField_startLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_startLinkActionPerformed(evt);
            }
        });

        jLabel_confLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("./resources/newNodo.png"))); // NOI18N
        jLabel_confLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_confLinkMouseClicked(evt);
            }
        });

        jTextField_endLink.setColumns(3);
        jTextField_endLink.setToolTipText("Nodo di arrivo");
        jTextField_endLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_endLinkActionPerformed(evt);
            }
        });

        jTextField_pesoLink.setColumns(3);
        jTextField_pesoLink.setToolTipText("Peso collegamento");
        jTextField_pesoLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pesoLinkActionPerformed(evt);
            }
        });

        jLabel8.setText("Esegui Dijkstra:");

        jTextField_startDijkstra.setColumns(3);
        jTextField_startDijkstra.setToolTipText("Nodo di partenza");

        jLabel_confDijkstra.setIcon(new javax.swing.ImageIcon(getClass().getResource("./resources/newNodo.png"))); // NOI18N
        jLabel_confDijkstra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_confDijkstraMouseClicked(evt);
            }
        });

        jLabel5.setText("Grafo");

        jLabel9.setText("Risultati");

        jTextArea_grafoStruct.setColumns(20);
        jTextArea_grafoStruct.setRows(5);
        jScrollPane1.setViewportView(jTextArea_grafoStruct);

        jTextArea_result.setColumns(20);
        jTextArea_result.setRows(5);
        jScrollPane2.setViewportView(jTextArea_result);

        jTextField_endDijkstra.setColumns(3);
        jTextField_endDijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_endDijkstraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_numNodi, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_confNumNodi))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jTextField_startDijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_endDijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel_confDijkstra))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jTextField_startLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_endLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_pesoLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_confLink))))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_numNodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel_confNumNodi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField_endLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_startLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_pesoLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_confLink))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_startDijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_endDijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_confDijkstra))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jLabel_confNumNodiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_confNumNodiMouseClicked
        // TODO add your handling code here:
        String str_input = jTextField_numNodi.getText();
        try{
          g = new Grafo(Integer.parseInt(str_input));//izializzazione nuovo grafo
          jTextArea_grafoStruct.setText(g.toString());        
        }catch(Exception e){
          JOptionPane.showMessageDialog(this, "Valore inserito non valido","Attenzione", JOptionPane.WARNING_MESSAGE);        
        }
    }//GEN-LAST:event_jLabel_confNumNodiMouseClicked

    private void jLabel_confLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_confLinkMouseClicked
        // TODO add your handling code here:
        String str_start = jTextField_startLink.getText();
        String str_end = jTextField_endLink.getText();
        String str_peso = jTextField_pesoLink.getText();
        int start,end;
        double peso;
        try{
          start =Integer.parseInt(str_start); 
          end = Integer.parseInt(str_end);
          peso = Double.parseDouble(str_peso);
          if(!g.esisteArco(start,end,peso)){//Evita la creazione di archi identici
             if(g.addArco(Integer.parseInt(str_start),Integer.parseInt(str_end),Double.parseDouble(str_peso)))
                jTextArea_grafoStruct.setText(g.toString());
             else //
                JOptionPane.showMessageDialog(this, "Uno o entrambi i nodi inseriti non si trovano nel grafo","Attenzione", JOptionPane.WARNING_MESSAGE);  
          }
          else
            JOptionPane.showMessageDialog(this, "Non si possono inserire archi identici.","Attenzione", JOptionPane.WARNING_MESSAGE);
        }catch(Exception e){
          JOptionPane.showMessageDialog(this, "Valori inseriti non validi","Attenzione", JOptionPane.WARNING_MESSAGE);        
        }
          
    }//GEN-LAST:event_jLabel_confLinkMouseClicked

    private void jTextField_startLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_startLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_startLinkActionPerformed

    private void jTextField_pesoLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pesoLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pesoLinkActionPerformed

    private void jTextField_endLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_endLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_endLinkActionPerformed

    private void jLabel_confDijkstraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_confDijkstraMouseClicked
        // TODO add your handling code here:
        String str_start = jTextField_startDijkstra.getText();
        String str_end = jTextField_endDijkstra.getText();
        int start=-1,end=-1;

        try{
          CamminiMinimi c = new CamminiMinimi(g);//Può fallire se il grafo ancora non esiste
          start = Integer.parseInt(str_start);//Può fallire se la string non è intera
          if(!str_end.equals(""))//Tenta la conversione solo se il campo NON è vuoto
            end = Integer.parseInt(str_end);//Può fallire se la string non è intera
          if(g.nodoValido(start)){
            c.exeDijkstra(start);  
            jTextArea_result.setText(c.toString());//Stampo tabella di Dijkstra
            if(g.nodoValido(end)){//Se viene inserito il nodo di arrivo
              jTextArea_result.setText(jTextArea_result.getText()+"\nCammino("+start+"->"+end+") : "+c.cammino(start,end));//Può fallire se str_end non è un intero
              System.out.println("cammino");
            }
          }
          else{
            JOptionPane.showMessageDialog(this, "Nodo di partenza non valido","Attenzione", JOptionPane.WARNING_MESSAGE);        
          }
              //jTextArea_result.setText(c.toString());//Stampo tabella di Dijkstra

        }catch(Exception e){
          JOptionPane.showMessageDialog(this, "Non è possibile eseguire Dijkstra","Attenzione", JOptionPane.WARNING_MESSAGE);        
        }        
        
    }//GEN-LAST:event_jLabel_confDijkstraMouseClicked

    private void jTextField_endDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_endDijkstraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_endDijkstraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MyFrame().setVisible(true);
            }
        });
    }
    //private Grafo gr;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_confDijkstra;
    private javax.swing.JLabel jLabel_confLink;
    private javax.swing.JLabel jLabel_confNumNodi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_grafoStruct;
    private javax.swing.JTextArea jTextArea_result;
    private javax.swing.JTextField jTextField_endDijkstra;
    private javax.swing.JTextField jTextField_endLink;
    private javax.swing.JTextField jTextField_numNodi;
    private javax.swing.JTextField jTextField_pesoLink;
    private javax.swing.JTextField jTextField_startDijkstra;
    private javax.swing.JTextField jTextField_startLink;
    // End of variables declaration//GEN-END:variables
}
